version: '3.6'
services:
  ldap:
    image: osixia/openldap
    container_name: ldap
    restart: always
    command: --copy-service # needed so it doesn't modify ./ldap/ldif
    environment:
      - LDAP_ORGANISATION=Example Org
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=changeme
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=changeme
    volumes:
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    
  db:
    image: postgres:11-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=pretix
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pgpw

  redis:
    image: redis:alpine
    restart: always
    container_name: redis

  pretix:
    build: ./pretix
    restart: always
    environment:
      - POSTGRES_DB=pretix
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pgpw
      - DJANGO_SECRET=insecure
      - INSTANCE_NAME=Example Org pretix
      - CURRENCY=EUR
    volumes:
      - ./pretix/etc/pretix:/etc/pretix
    depends_on:
      - db
      - redis
    command: all
    ports:
      - "80:80"

volumes:
  ldap_data:
  ldap_config:
