on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: null

name: Create Release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: nicknovitski/nix-develop@v1
    - name: Lint with flake8
      run: |
        cd src
        flake8 --version
        flake8
    - name: Test with pytest
      run: |
        cd src/tests
        pytest --version
        pytest
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: release
    needs: test
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -U setuptools wheel twine
      - name: Build
        run: |
          cd src
          python setup.py sdist bdist_wheel
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
